/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class native1_NativeDemo */

#ifndef _Included_native1_NativeDemo
#define _Included_native1_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     native1_NativeDemo
 * Method:    greet1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_native1_NativeDemo_greet1
  (JNIEnv *, jobject);

/*
 * Class:     native1_NativeDemo
 * Method:    greet2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_native1_NativeDemo_greet2
  (JNIEnv *, jclass);

/*
 * Class:     native1_NativeDemo
 * Method:    greet3
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_native1_NativeDemo_greet3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
