package mypack;

// Generated 25 Jul, 2016 9:46:09 AM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Moviesong generated by hbm2java
 */
@Entity
@Table(name = "moviesong", catalog = "mydb")
public class Moviesong implements java.io.Serializable {

	private int id;
	private String movieName;
	private String songName;

	public Moviesong() {
	}

	public Moviesong(int id) {
		this.id = id;
	}

	public Moviesong(int id, String movieName, String songName) {
		this.id = id;
		this.movieName = movieName;
		this.songName = songName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "movieName", length = 30)
	public String getMovieName() {
		return this.movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

	@Column(name = "songName", length = 30)
	public String getSongName() {
		return this.songName;
	}

	public void setSongName(String songName) {
		this.songName = songName;
	}

}
