/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeDemo */

#ifndef _Included_NativeDemo
#define _Included_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeDemo
 * Method:    greet1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeDemo_greet1
  (JNIEnv *, jobject);

/*
 * Class:     NativeDemo
 * Method:    greet2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeDemo_greet2
  (JNIEnv *, jclass);

/*
 * Class:     NativeDemo
 * Method:    greet3
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeDemo_greet3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
